import type { PrismaClient } from '../generated/client';

/**
 * US-897-033's governance criterion: purpose/owner/frequency/source/
 * filters/measures as real, inspectable rows for every report this company
 * can run — not invented ahead of a consumer any more, since the web app's
 * own reports index (apps/web/.../ledger/reports/page.tsx) now reads these
 * rows instead of its old hardcoded array. Kept in its own file, same
 * pattern as seed-kpi-definitions.ts.
 */
const REPORT_DEFINITIONS = [
  {
    key: 'trial-balance',
    name: 'Trial balance',
    purpose: 'Every account and its balance, proving the ledger is internally consistent before any statement is trusted.',
    owner: 'Finance Controller',
    frequency: 'On demand',
    source: 'TrialBalanceService.build() — apps/api/src/reporting/trial-balance.service.ts',
    filters: ['financialYearId', 'financialPeriodId', 'branchId', 'costCentreId', 'farmId'],
    measures: ['accountNumber', 'accountName', 'totalDebitKobo', 'totalCreditKobo', 'displayedBalanceKobo', 'balanced'],
    webPath: '/ledger/trial-balance',
    apiEndpoint: 'GET /reporting/trial-balance',
    exportSupported: true,
    drillThroughSupported: true,
  },
  {
    key: 'profit-loss',
    name: 'Profit & loss',
    purpose: 'Revenue, cost of sales and operating expense for a period, so a farm knows if it made money.',
    owner: 'Finance Controller',
    frequency: 'Monthly close',
    source: 'ProfitLossService.build() — apps/api/src/reporting/profit-loss.service.ts',
    filters: ['financialYearId', 'financialPeriodId', 'branchId', 'costCentreId', 'farmId'],
    measures: ['revenueKobo', 'costOfSalesKobo', 'grossProfitKobo', 'operatingExpenseKobo', 'profitBeforeTaxKobo'],
    webPath: '/ledger/profit-loss',
    apiEndpoint: 'GET /reporting/profit-loss',
    exportSupported: true,
    drillThroughSupported: false,
  },
  {
    key: 'balance-sheet',
    name: 'Balance sheet',
    purpose: 'What the company owns, owes, and is worth, as at today — assets must equal liabilities plus equity.',
    owner: 'Finance Controller',
    frequency: 'Monthly close',
    source: 'BalanceSheetService.build() — apps/api/src/reporting/balance-sheet.service.ts',
    filters: ['branchId', 'costCentreId', 'farmId'],
    measures: ['assets', 'liabilities', 'equity', 'totalAssetsKobo', 'totalLiabilitiesAndEquityKobo', 'balanced'],
    webPath: '/ledger/balance-sheet',
    apiEndpoint: 'GET /reporting/balance-sheet',
    exportSupported: true,
    drillThroughSupported: false,
  },
  {
    key: 'cash-flow',
    name: 'Cash flow',
    purpose: 'Where the cash moved for one period (indirect method), so closing cash can be reconciled to the balance sheet.',
    owner: 'Finance Controller',
    frequency: 'Monthly close',
    source: 'CashFlowService.build() — apps/api/src/reporting/cash-flow.service.ts',
    filters: ['financialPeriodId'],
    measures: ['openingCashKobo', 'netMovementKobo', 'closingCashKobo', 'reconciled'],
    webPath: '/ledger/cash-flow',
    apiEndpoint: 'GET /reporting/cash-flow',
    exportSupported: true,
    drillThroughSupported: false,
  },
  {
    key: 'fixed-assets',
    name: 'Fixed assets',
    purpose: 'The asset register and depreciation runs, so PPE and depreciation are traceable to individual assets.',
    owner: 'FA Accountant',
    frequency: 'On demand',
    source: 'FixedAssetService.listAssets() — apps/api/src/fixed-assets/fixed-asset.service.ts',
    filters: [],
    measures: ['assetNumber', 'costKobo', 'accumulatedDepreciationKobo', 'netBookValueKobo', 'status', 'disposedOn'],
    webPath: '/ledger/fixed-assets',
    apiEndpoint: 'GET /fixed-assets/assets',
    exportSupported: false,
    drillThroughSupported: false,
  },
  {
    key: 'kpis',
    name: 'KPIs',
    purpose: 'Nine measures management uses to make decisions, each computed or explicitly refused with a reason.',
    owner: 'CFO',
    frequency: 'On demand',
    source: 'KpiService.build() — apps/api/src/reporting/kpi.service.ts',
    filters: ['farmId', 'groupId', 'financialYearId'],
    measures: ['key', 'label', 'value', 'format', 'computable', 'reason'],
    webPath: '/ledger/kpis',
    apiEndpoint: 'GET /reporting/kpis',
    exportSupported: false,
    drillThroughSupported: true,
  },
  {
    key: 'ar-ageing',
    name: 'AR ageing',
    purpose: 'Who owes the company, and how overdue it is, by customer.',
    owner: 'Finance Manager',
    frequency: 'Weekly',
    source: 'CustomerReceiptService.ageing() — apps/api/src/sales/customer-receipt.service.ts',
    filters: [],
    measures: ['customer', 'current', '30Days', '60Days', '90PlusDays', 'totalKobo'],
    webPath: '/ledger/ar-ageing',
    apiEndpoint: 'GET /reporting/ar-ageing',
    exportSupported: true,
    drillThroughSupported: false,
  },
  {
    key: 'ap-ageing',
    name: 'AP ageing',
    purpose: 'Who the company owes, and how overdue it is, by supplier.',
    owner: 'Finance Manager',
    frequency: 'Weekly',
    source: 'SupplierPaymentService.ageing() — apps/api/src/procurement/supplier-payment.service.ts',
    filters: [],
    measures: ['supplier', 'current', '30Days', '60Days', '90PlusDays', 'totalKobo'],
    webPath: '/ledger/ap-ageing',
    apiEndpoint: 'GET /reporting/ap-ageing',
    exportSupported: true,
    drillThroughSupported: false,
  },
  {
    key: 'journals',
    name: 'Journal entries',
    purpose: 'Every posting in the ledger, whichever module raised it — the register every other report ultimately derives from.',
    owner: 'Internal Auditor',
    frequency: 'On demand',
    source: 'ReportingController.journals() — apps/api/src/reporting/reporting.controller.ts',
    filters: ['financialYearId', 'financialPeriodId', 'status', 'search', 'page'],
    measures: ['journalNumber', 'journalDate', 'status', 'sourceModule', 'totalDebitKobo', 'totalCreditKobo'],
    webPath: '/ledger/journals',
    apiEndpoint: 'GET /reporting/journals',
    exportSupported: false,
    drillThroughSupported: false,
  },
  {
    key: 'audit',
    name: 'Audit trail',
    purpose: 'Who did what, when, and what changed — Rule 9, append-only at the database.',
    owner: 'Internal Auditor',
    frequency: 'On demand',
    source: 'ReportingController.audit() — apps/api/src/reporting/reporting.controller.ts',
    filters: ['module', 'search', 'page'],
    measures: ['entityType', 'action', 'userId', 'occurredAt', 'oldValueJson', 'newValueJson'],
    webPath: '/ledger/audit',
    apiEndpoint: 'GET /reporting/audit',
    exportSupported: false,
    drillThroughSupported: false,
  },
] as const;

export async function seedReportDefinitions(prisma: PrismaClient, companyId: string) {
  for (const def of REPORT_DEFINITIONS) {
    await prisma.reportDefinition.upsert({
      where: { companyId_key: { companyId, key: def.key } },
      update: {
        name: def.name,
        purpose: def.purpose,
        owner: def.owner,
        frequency: def.frequency,
        source: def.source,
        filters: [...def.filters],
        measures: [...def.measures],
        webPath: def.webPath,
        apiEndpoint: def.apiEndpoint,
        exportSupported: def.exportSupported,
        drillThroughSupported: def.drillThroughSupported,
      },
      create: {
        companyId,
        key: def.key,
        name: def.name,
        purpose: def.purpose,
        owner: def.owner,
        frequency: def.frequency,
        source: def.source,
        filters: [...def.filters],
        measures: [...def.measures],
        webPath: def.webPath,
        apiEndpoint: def.apiEndpoint,
        exportSupported: def.exportSupported,
        drillThroughSupported: def.drillThroughSupported,
      },
    });
  }
  console.log(`Seeded ${REPORT_DEFINITIONS.length} report definitions.`);
  return REPORT_DEFINITIONS.length;
}
